// source: idep/token/tx.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
goog.exportSymbol('proto.idep.token.MsgEditToken', null, global);
goog.exportSymbol('proto.idep.token.MsgEditTokenResponse', null, global);
goog.exportSymbol('proto.idep.token.MsgIssueToken', null, global);
goog.exportSymbol('proto.idep.token.MsgIssueTokenResponse', null, global);
goog.exportSymbol('proto.idep.token.MsgMintToken', null, global);
goog.exportSymbol('proto.idep.token.MsgMintTokenResponse', null, global);
goog.exportSymbol('proto.idep.token.MsgTransferTokenOwner', null, global);
goog.exportSymbol(
  'proto.idep.token.MsgTransferTokenOwnerResponse',
  null,
  global
);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.token.MsgIssueToken = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.token.MsgIssueToken, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.token.MsgIssueToken.displayName = 'proto.idep.token.MsgIssueToken';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.token.MsgIssueTokenResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.token.MsgIssueTokenResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.token.MsgIssueTokenResponse.displayName =
    'proto.idep.token.MsgIssueTokenResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.token.MsgTransferTokenOwner = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.token.MsgTransferTokenOwner, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.token.MsgTransferTokenOwner.displayName =
    'proto.idep.token.MsgTransferTokenOwner';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.token.MsgTransferTokenOwnerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.token.MsgTransferTokenOwnerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.token.MsgTransferTokenOwnerResponse.displayName =
    'proto.idep.token.MsgTransferTokenOwnerResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.token.MsgEditToken = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.token.MsgEditToken, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.token.MsgEditToken.displayName = 'proto.idep.token.MsgEditToken';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.token.MsgEditTokenResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.token.MsgEditTokenResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.token.MsgEditTokenResponse.displayName =
    'proto.idep.token.MsgEditTokenResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.token.MsgMintToken = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.token.MsgMintToken, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.token.MsgMintToken.displayName = 'proto.idep.token.MsgMintToken';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.token.MsgMintTokenResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.token.MsgMintTokenResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.token.MsgMintTokenResponse.displayName =
    'proto.idep.token.MsgMintTokenResponse';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.token.MsgIssueToken.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.token.MsgIssueToken.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.token.MsgIssueToken} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.token.MsgIssueToken.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        symbol: jspb.Message.getFieldWithDefault(msg, 1, ''),
        name: jspb.Message.getFieldWithDefault(msg, 2, ''),
        scale: jspb.Message.getFieldWithDefault(msg, 3, 0),
        minUnit: jspb.Message.getFieldWithDefault(msg, 4, ''),
        initialSupply: jspb.Message.getFieldWithDefault(msg, 5, 0),
        maxSupply: jspb.Message.getFieldWithDefault(msg, 6, 0),
        mintable: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
        owner: jspb.Message.getFieldWithDefault(msg, 8, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.token.MsgIssueToken}
 */
proto.idep.token.MsgIssueToken.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.token.MsgIssueToken();
  return proto.idep.token.MsgIssueToken.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.token.MsgIssueToken} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.token.MsgIssueToken}
 */
proto.idep.token.MsgIssueToken.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setSymbol(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setName(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readUint32());
        msg.setScale(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setMinUnit(value);
        break;
      case 5:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setInitialSupply(value);
        break;
      case 6:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setMaxSupply(value);
        break;
      case 7:
        var value = /** @type {boolean} */ (reader.readBool());
        msg.setMintable(value);
        break;
      case 8:
        var value = /** @type {string} */ (reader.readString());
        msg.setOwner(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.token.MsgIssueToken.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.token.MsgIssueToken.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.token.MsgIssueToken} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.token.MsgIssueToken.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getScale();
  if (f !== 0) {
    writer.writeUint32(3, f);
  }
  f = message.getMinUnit();
  if (f.length > 0) {
    writer.writeString(4, f);
  }
  f = message.getInitialSupply();
  if (f !== 0) {
    writer.writeUint64(5, f);
  }
  f = message.getMaxSupply();
  if (f !== 0) {
    writer.writeUint64(6, f);
  }
  f = message.getMintable();
  if (f) {
    writer.writeBool(7, f);
  }
  f = message.getOwner();
  if (f.length > 0) {
    writer.writeString(8, f);
  }
};

/**
 * optional string symbol = 1;
 * @return {string}
 */
proto.idep.token.MsgIssueToken.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgIssueToken} returns this
 */
proto.idep.token.MsgIssueToken.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string name = 2;
 * @return {string}
 */
proto.idep.token.MsgIssueToken.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgIssueToken} returns this
 */
proto.idep.token.MsgIssueToken.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional uint32 scale = 3;
 * @return {number}
 */
proto.idep.token.MsgIssueToken.prototype.getScale = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.token.MsgIssueToken} returns this
 */
proto.idep.token.MsgIssueToken.prototype.setScale = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};

/**
 * optional string min_unit = 4;
 * @return {string}
 */
proto.idep.token.MsgIssueToken.prototype.getMinUnit = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgIssueToken} returns this
 */
proto.idep.token.MsgIssueToken.prototype.setMinUnit = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * optional uint64 initial_supply = 5;
 * @return {number}
 */
proto.idep.token.MsgIssueToken.prototype.getInitialSupply = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.token.MsgIssueToken} returns this
 */
proto.idep.token.MsgIssueToken.prototype.setInitialSupply = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};

/**
 * optional uint64 max_supply = 6;
 * @return {number}
 */
proto.idep.token.MsgIssueToken.prototype.getMaxSupply = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.token.MsgIssueToken} returns this
 */
proto.idep.token.MsgIssueToken.prototype.setMaxSupply = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};

/**
 * optional bool mintable = 7;
 * @return {boolean}
 */
proto.idep.token.MsgIssueToken.prototype.getMintable = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(
    this,
    7,
    false
  ));
};

/**
 * @param {boolean} value
 * @return {!proto.idep.token.MsgIssueToken} returns this
 */
proto.idep.token.MsgIssueToken.prototype.setMintable = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};

/**
 * optional string owner = 8;
 * @return {string}
 */
proto.idep.token.MsgIssueToken.prototype.getOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgIssueToken} returns this
 */
proto.idep.token.MsgIssueToken.prototype.setOwner = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.token.MsgIssueTokenResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.token.MsgIssueTokenResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.token.MsgIssueTokenResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.token.MsgIssueTokenResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {};

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.token.MsgIssueTokenResponse}
 */
proto.idep.token.MsgIssueTokenResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.token.MsgIssueTokenResponse();
  return proto.idep.token.MsgIssueTokenResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.token.MsgIssueTokenResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.token.MsgIssueTokenResponse}
 */
proto.idep.token.MsgIssueTokenResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.token.MsgIssueTokenResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.token.MsgIssueTokenResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.token.MsgIssueTokenResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.token.MsgIssueTokenResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.token.MsgTransferTokenOwner.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.token.MsgTransferTokenOwner.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.token.MsgTransferTokenOwner} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.token.MsgTransferTokenOwner.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        srcOwner: jspb.Message.getFieldWithDefault(msg, 1, ''),
        dstOwner: jspb.Message.getFieldWithDefault(msg, 2, ''),
        symbol: jspb.Message.getFieldWithDefault(msg, 3, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.token.MsgTransferTokenOwner}
 */
proto.idep.token.MsgTransferTokenOwner.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.token.MsgTransferTokenOwner();
  return proto.idep.token.MsgTransferTokenOwner.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.token.MsgTransferTokenOwner} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.token.MsgTransferTokenOwner}
 */
proto.idep.token.MsgTransferTokenOwner.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setSrcOwner(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setDstOwner(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setSymbol(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.token.MsgTransferTokenOwner.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.token.MsgTransferTokenOwner.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.token.MsgTransferTokenOwner} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.token.MsgTransferTokenOwner.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getSrcOwner();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getDstOwner();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
};

/**
 * optional string src_owner = 1;
 * @return {string}
 */
proto.idep.token.MsgTransferTokenOwner.prototype.getSrcOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgTransferTokenOwner} returns this
 */
proto.idep.token.MsgTransferTokenOwner.prototype.setSrcOwner = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string dst_owner = 2;
 * @return {string}
 */
proto.idep.token.MsgTransferTokenOwner.prototype.getDstOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgTransferTokenOwner} returns this
 */
proto.idep.token.MsgTransferTokenOwner.prototype.setDstOwner = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional string symbol = 3;
 * @return {string}
 */
proto.idep.token.MsgTransferTokenOwner.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgTransferTokenOwner} returns this
 */
proto.idep.token.MsgTransferTokenOwner.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.token.MsgTransferTokenOwnerResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.token.MsgTransferTokenOwnerResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.token.MsgTransferTokenOwnerResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.token.MsgTransferTokenOwnerResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {};

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.token.MsgTransferTokenOwnerResponse}
 */
proto.idep.token.MsgTransferTokenOwnerResponse.deserializeBinary = function(
  bytes
) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.token.MsgTransferTokenOwnerResponse();
  return proto.idep.token.MsgTransferTokenOwnerResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.token.MsgTransferTokenOwnerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.token.MsgTransferTokenOwnerResponse}
 */
proto.idep.token.MsgTransferTokenOwnerResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.token.MsgTransferTokenOwnerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.token.MsgTransferTokenOwnerResponse.serializeBinaryToWriter(
    this,
    writer
  );
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.token.MsgTransferTokenOwnerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.token.MsgTransferTokenOwnerResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.token.MsgEditToken.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.token.MsgEditToken.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.token.MsgEditToken} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.token.MsgEditToken.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        symbol: jspb.Message.getFieldWithDefault(msg, 1, ''),
        name: jspb.Message.getFieldWithDefault(msg, 2, ''),
        maxSupply: jspb.Message.getFieldWithDefault(msg, 3, 0),
        mintable: jspb.Message.getFieldWithDefault(msg, 4, ''),
        owner: jspb.Message.getFieldWithDefault(msg, 5, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.token.MsgEditToken}
 */
proto.idep.token.MsgEditToken.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.token.MsgEditToken();
  return proto.idep.token.MsgEditToken.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.token.MsgEditToken} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.token.MsgEditToken}
 */
proto.idep.token.MsgEditToken.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setSymbol(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setName(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setMaxSupply(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setMintable(value);
        break;
      case 5:
        var value = /** @type {string} */ (reader.readString());
        msg.setOwner(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.token.MsgEditToken.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.token.MsgEditToken.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.token.MsgEditToken} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.token.MsgEditToken.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getMaxSupply();
  if (f !== 0) {
    writer.writeUint64(3, f);
  }
  f = message.getMintable();
  if (f.length > 0) {
    writer.writeString(4, f);
  }
  f = message.getOwner();
  if (f.length > 0) {
    writer.writeString(5, f);
  }
};

/**
 * optional string symbol = 1;
 * @return {string}
 */
proto.idep.token.MsgEditToken.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgEditToken} returns this
 */
proto.idep.token.MsgEditToken.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string name = 2;
 * @return {string}
 */
proto.idep.token.MsgEditToken.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgEditToken} returns this
 */
proto.idep.token.MsgEditToken.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional uint64 max_supply = 3;
 * @return {number}
 */
proto.idep.token.MsgEditToken.prototype.getMaxSupply = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.token.MsgEditToken} returns this
 */
proto.idep.token.MsgEditToken.prototype.setMaxSupply = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};

/**
 * optional string mintable = 4;
 * @return {string}
 */
proto.idep.token.MsgEditToken.prototype.getMintable = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgEditToken} returns this
 */
proto.idep.token.MsgEditToken.prototype.setMintable = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * optional string owner = 5;
 * @return {string}
 */
proto.idep.token.MsgEditToken.prototype.getOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgEditToken} returns this
 */
proto.idep.token.MsgEditToken.prototype.setOwner = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.token.MsgEditTokenResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.token.MsgEditTokenResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.token.MsgEditTokenResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.token.MsgEditTokenResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {};

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.token.MsgEditTokenResponse}
 */
proto.idep.token.MsgEditTokenResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.token.MsgEditTokenResponse();
  return proto.idep.token.MsgEditTokenResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.token.MsgEditTokenResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.token.MsgEditTokenResponse}
 */
proto.idep.token.MsgEditTokenResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.token.MsgEditTokenResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.token.MsgEditTokenResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.token.MsgEditTokenResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.token.MsgEditTokenResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.token.MsgMintToken.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.token.MsgMintToken.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.token.MsgMintToken} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.token.MsgMintToken.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        symbol: jspb.Message.getFieldWithDefault(msg, 1, ''),
        amount: jspb.Message.getFieldWithDefault(msg, 2, 0),
        to: jspb.Message.getFieldWithDefault(msg, 3, ''),
        owner: jspb.Message.getFieldWithDefault(msg, 4, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.token.MsgMintToken}
 */
proto.idep.token.MsgMintToken.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.token.MsgMintToken();
  return proto.idep.token.MsgMintToken.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.token.MsgMintToken} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.token.MsgMintToken}
 */
proto.idep.token.MsgMintToken.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setSymbol(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setAmount(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setTo(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setOwner(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.token.MsgMintToken.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.token.MsgMintToken.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.token.MsgMintToken} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.token.MsgMintToken.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getAmount();
  if (f !== 0) {
    writer.writeUint64(2, f);
  }
  f = message.getTo();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getOwner();
  if (f.length > 0) {
    writer.writeString(4, f);
  }
};

/**
 * optional string symbol = 1;
 * @return {string}
 */
proto.idep.token.MsgMintToken.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgMintToken} returns this
 */
proto.idep.token.MsgMintToken.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional uint64 amount = 2;
 * @return {number}
 */
proto.idep.token.MsgMintToken.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.token.MsgMintToken} returns this
 */
proto.idep.token.MsgMintToken.prototype.setAmount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};

/**
 * optional string to = 3;
 * @return {string}
 */
proto.idep.token.MsgMintToken.prototype.getTo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgMintToken} returns this
 */
proto.idep.token.MsgMintToken.prototype.setTo = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional string owner = 4;
 * @return {string}
 */
proto.idep.token.MsgMintToken.prototype.getOwner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.token.MsgMintToken} returns this
 */
proto.idep.token.MsgMintToken.prototype.setOwner = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.token.MsgMintTokenResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.token.MsgMintTokenResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.token.MsgMintTokenResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.token.MsgMintTokenResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {};

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.token.MsgMintTokenResponse}
 */
proto.idep.token.MsgMintTokenResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.token.MsgMintTokenResponse();
  return proto.idep.token.MsgMintTokenResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.token.MsgMintTokenResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.token.MsgMintTokenResponse}
 */
proto.idep.token.MsgMintTokenResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.token.MsgMintTokenResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.token.MsgMintTokenResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.token.MsgMintTokenResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.token.MsgMintTokenResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
};

goog.object.extend(exports, proto.idep.token);
