// source: idep/oracle/query.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var idep_oracle_oracle_pb = require('../../idep/oracle/oracle_pb.js');
goog.object.extend(proto, idep_oracle_oracle_pb);
var idep_service_service_pb = require('../../idep/service/service_pb.js');
goog.object.extend(proto, idep_service_service_pb);
var gogoproto_gogo_pb = require('../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var google_api_annotations_pb = require('../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var cosmos_base_v1beta1_coin_pb = require('../../cosmos/base/v1beta1/coin_pb.js');
goog.object.extend(proto, cosmos_base_v1beta1_coin_pb);
goog.exportSymbol('proto.idep.oracle.FeedContext', null, global);
goog.exportSymbol('proto.idep.oracle.QueryFeedRequest', null, global);
goog.exportSymbol('proto.idep.oracle.QueryFeedResponse', null, global);
goog.exportSymbol('proto.idep.oracle.QueryFeedValueRequest', null, global);
goog.exportSymbol('proto.idep.oracle.QueryFeedValueResponse', null, global);
goog.exportSymbol('proto.idep.oracle.QueryFeedsRequest', null, global);
goog.exportSymbol('proto.idep.oracle.QueryFeedsResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.QueryFeedRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.QueryFeedRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.QueryFeedRequest.displayName =
    'proto.idep.oracle.QueryFeedRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.QueryFeedResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.QueryFeedResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.QueryFeedResponse.displayName =
    'proto.idep.oracle.QueryFeedResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.QueryFeedsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.QueryFeedsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.QueryFeedsRequest.displayName =
    'proto.idep.oracle.QueryFeedsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.QueryFeedsResponse = function(opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.idep.oracle.QueryFeedsResponse.repeatedFields_,
    null
  );
};
goog.inherits(proto.idep.oracle.QueryFeedsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.QueryFeedsResponse.displayName =
    'proto.idep.oracle.QueryFeedsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.QueryFeedValueRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.QueryFeedValueRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.QueryFeedValueRequest.displayName =
    'proto.idep.oracle.QueryFeedValueRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.QueryFeedValueResponse = function(opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.idep.oracle.QueryFeedValueResponse.repeatedFields_,
    null
  );
};
goog.inherits(proto.idep.oracle.QueryFeedValueResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.QueryFeedValueResponse.displayName =
    'proto.idep.oracle.QueryFeedValueResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.FeedContext = function(opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.idep.oracle.FeedContext.repeatedFields_,
    null
  );
};
goog.inherits(proto.idep.oracle.FeedContext, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.FeedContext.displayName = 'proto.idep.oracle.FeedContext';
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.QueryFeedRequest.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.QueryFeedRequest.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.QueryFeedRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.QueryFeedRequest.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        feedName: jspb.Message.getFieldWithDefault(msg, 1, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.QueryFeedRequest}
 */
proto.idep.oracle.QueryFeedRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.QueryFeedRequest();
  return proto.idep.oracle.QueryFeedRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.QueryFeedRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.QueryFeedRequest}
 */
proto.idep.oracle.QueryFeedRequest.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setFeedName(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.QueryFeedRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.QueryFeedRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.QueryFeedRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.QueryFeedRequest.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeedName();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
};

/**
 * optional string feed_name = 1;
 * @return {string}
 */
proto.idep.oracle.QueryFeedRequest.prototype.getFeedName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.QueryFeedRequest} returns this
 */
proto.idep.oracle.QueryFeedRequest.prototype.setFeedName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.QueryFeedResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.QueryFeedResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.QueryFeedResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.QueryFeedResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        feed:
          (f = msg.getFeed()) &&
          proto.idep.oracle.FeedContext.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.QueryFeedResponse}
 */
proto.idep.oracle.QueryFeedResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.QueryFeedResponse();
  return proto.idep.oracle.QueryFeedResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.QueryFeedResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.QueryFeedResponse}
 */
proto.idep.oracle.QueryFeedResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.idep.oracle.FeedContext();
        reader.readMessage(
          value,
          proto.idep.oracle.FeedContext.deserializeBinaryFromReader
        );
        msg.setFeed(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.QueryFeedResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.QueryFeedResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.QueryFeedResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.QueryFeedResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeed();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.idep.oracle.FeedContext.serializeBinaryToWriter
    );
  }
};

/**
 * optional FeedContext feed = 1;
 * @return {?proto.idep.oracle.FeedContext}
 */
proto.idep.oracle.QueryFeedResponse.prototype.getFeed = function() {
  return /** @type{?proto.idep.oracle.FeedContext} */ (jspb.Message.getWrapperField(
    this,
    proto.idep.oracle.FeedContext,
    1
  ));
};

/**
 * @param {?proto.idep.oracle.FeedContext|undefined} value
 * @return {!proto.idep.oracle.QueryFeedResponse} returns this
 */
proto.idep.oracle.QueryFeedResponse.prototype.setFeed = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.idep.oracle.QueryFeedResponse} returns this
 */
proto.idep.oracle.QueryFeedResponse.prototype.clearFeed = function() {
  return this.setFeed(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idep.oracle.QueryFeedResponse.prototype.hasFeed = function() {
  return jspb.Message.getField(this, 1) != null;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.QueryFeedsRequest.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.QueryFeedsRequest.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.QueryFeedsRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.QueryFeedsRequest.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        state: jspb.Message.getFieldWithDefault(msg, 1, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.QueryFeedsRequest}
 */
proto.idep.oracle.QueryFeedsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.QueryFeedsRequest();
  return proto.idep.oracle.QueryFeedsRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.QueryFeedsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.QueryFeedsRequest}
 */
proto.idep.oracle.QueryFeedsRequest.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setState(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.QueryFeedsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.QueryFeedsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.QueryFeedsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.QueryFeedsRequest.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
};

/**
 * optional string state = 1;
 * @return {string}
 */
proto.idep.oracle.QueryFeedsRequest.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.QueryFeedsRequest} returns this
 */
proto.idep.oracle.QueryFeedsRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idep.oracle.QueryFeedsResponse.repeatedFields_ = [1];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.QueryFeedsResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.QueryFeedsResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.QueryFeedsResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.QueryFeedsResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        feedsList: jspb.Message.toObjectList(
          msg.getFeedsList(),
          proto.idep.oracle.FeedContext.toObject,
          includeInstance
        ),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.QueryFeedsResponse}
 */
proto.idep.oracle.QueryFeedsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.QueryFeedsResponse();
  return proto.idep.oracle.QueryFeedsResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.QueryFeedsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.QueryFeedsResponse}
 */
proto.idep.oracle.QueryFeedsResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.idep.oracle.FeedContext();
        reader.readMessage(
          value,
          proto.idep.oracle.FeedContext.deserializeBinaryFromReader
        );
        msg.addFeeds(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.QueryFeedsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.QueryFeedsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.QueryFeedsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.QueryFeedsResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeedsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.idep.oracle.FeedContext.serializeBinaryToWriter
    );
  }
};

/**
 * repeated FeedContext feeds = 1;
 * @return {!Array<!proto.idep.oracle.FeedContext>}
 */
proto.idep.oracle.QueryFeedsResponse.prototype.getFeedsList = function() {
  return /** @type{!Array<!proto.idep.oracle.FeedContext>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    proto.idep.oracle.FeedContext,
    1
  ));
};

/**
 * @param {!Array<!proto.idep.oracle.FeedContext>} value
 * @return {!proto.idep.oracle.QueryFeedsResponse} returns this
 */
proto.idep.oracle.QueryFeedsResponse.prototype.setFeedsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};

/**
 * @param {!proto.idep.oracle.FeedContext=} opt_value
 * @param {number=} opt_index
 * @return {!proto.idep.oracle.FeedContext}
 */
proto.idep.oracle.QueryFeedsResponse.prototype.addFeeds = function(
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.idep.oracle.FeedContext,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.oracle.QueryFeedsResponse} returns this
 */
proto.idep.oracle.QueryFeedsResponse.prototype.clearFeedsList = function() {
  return this.setFeedsList([]);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.QueryFeedValueRequest.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.QueryFeedValueRequest.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.QueryFeedValueRequest} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.QueryFeedValueRequest.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        feedName: jspb.Message.getFieldWithDefault(msg, 1, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.QueryFeedValueRequest}
 */
proto.idep.oracle.QueryFeedValueRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.QueryFeedValueRequest();
  return proto.idep.oracle.QueryFeedValueRequest.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.QueryFeedValueRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.QueryFeedValueRequest}
 */
proto.idep.oracle.QueryFeedValueRequest.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setFeedName(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.QueryFeedValueRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.QueryFeedValueRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.QueryFeedValueRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.QueryFeedValueRequest.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeedName();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
};

/**
 * optional string feed_name = 1;
 * @return {string}
 */
proto.idep.oracle.QueryFeedValueRequest.prototype.getFeedName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.QueryFeedValueRequest} returns this
 */
proto.idep.oracle.QueryFeedValueRequest.prototype.setFeedName = function(
  value
) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idep.oracle.QueryFeedValueResponse.repeatedFields_ = [1];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.QueryFeedValueResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.QueryFeedValueResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.QueryFeedValueResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.QueryFeedValueResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {
        feedValuesList: jspb.Message.toObjectList(
          msg.getFeedValuesList(),
          idep_oracle_oracle_pb.FeedValue.toObject,
          includeInstance
        ),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.QueryFeedValueResponse}
 */
proto.idep.oracle.QueryFeedValueResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.QueryFeedValueResponse();
  return proto.idep.oracle.QueryFeedValueResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.QueryFeedValueResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.QueryFeedValueResponse}
 */
proto.idep.oracle.QueryFeedValueResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new idep_oracle_oracle_pb.FeedValue();
        reader.readMessage(
          value,
          idep_oracle_oracle_pb.FeedValue.deserializeBinaryFromReader
        );
        msg.addFeedValues(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.QueryFeedValueResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.QueryFeedValueResponse.serializeBinaryToWriter(
    this,
    writer
  );
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.QueryFeedValueResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.QueryFeedValueResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeedValuesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      idep_oracle_oracle_pb.FeedValue.serializeBinaryToWriter
    );
  }
};

/**
 * repeated FeedValue feed_values = 1;
 * @return {!Array<!proto.idep.oracle.FeedValue>}
 */
proto.idep.oracle.QueryFeedValueResponse.prototype.getFeedValuesList = function() {
  return /** @type{!Array<!proto.idep.oracle.FeedValue>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    idep_oracle_oracle_pb.FeedValue,
    1
  ));
};

/**
 * @param {!Array<!proto.idep.oracle.FeedValue>} value
 * @return {!proto.idep.oracle.QueryFeedValueResponse} returns this
 */
proto.idep.oracle.QueryFeedValueResponse.prototype.setFeedValuesList = function(
  value
) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};

/**
 * @param {!proto.idep.oracle.FeedValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.idep.oracle.FeedValue}
 */
proto.idep.oracle.QueryFeedValueResponse.prototype.addFeedValues = function(
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.idep.oracle.FeedValue,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.oracle.QueryFeedValueResponse} returns this
 */
proto.idep.oracle.QueryFeedValueResponse.prototype.clearFeedValuesList = function() {
  return this.setFeedValuesList([]);
};

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idep.oracle.FeedContext.repeatedFields_ = [3, 6];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.FeedContext.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.FeedContext.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.FeedContext} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.FeedContext.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        feed:
          (f = msg.getFeed()) &&
          idep_oracle_oracle_pb.Feed.toObject(includeInstance, f),
        serviceName: jspb.Message.getFieldWithDefault(msg, 2, ''),
        providersList:
          (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
        input: jspb.Message.getFieldWithDefault(msg, 4, ''),
        timeout: jspb.Message.getFieldWithDefault(msg, 5, 0),
        serviceFeeCapList: jspb.Message.toObjectList(
          msg.getServiceFeeCapList(),
          cosmos_base_v1beta1_coin_pb.Coin.toObject,
          includeInstance
        ),
        repeatedFrequency: jspb.Message.getFieldWithDefault(msg, 7, 0),
        responseThreshold: jspb.Message.getFieldWithDefault(msg, 8, 0),
        state: jspb.Message.getFieldWithDefault(msg, 9, 0),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.FeedContext}
 */
proto.idep.oracle.FeedContext.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.FeedContext();
  return proto.idep.oracle.FeedContext.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.FeedContext} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.FeedContext}
 */
proto.idep.oracle.FeedContext.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new idep_oracle_oracle_pb.Feed();
        reader.readMessage(
          value,
          idep_oracle_oracle_pb.Feed.deserializeBinaryFromReader
        );
        msg.setFeed(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setServiceName(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.addProviders(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setInput(value);
        break;
      case 5:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setTimeout(value);
        break;
      case 6:
        var value = new cosmos_base_v1beta1_coin_pb.Coin();
        reader.readMessage(
          value,
          cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader
        );
        msg.addServiceFeeCap(value);
        break;
      case 7:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setRepeatedFrequency(value);
        break;
      case 8:
        var value = /** @type {number} */ (reader.readUint32());
        msg.setResponseThreshold(value);
        break;
      case 9:
        var value = /** @type {!proto.idep.service.RequestContextState} */ (reader.readEnum());
        msg.setState(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.FeedContext.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.FeedContext.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.FeedContext} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.FeedContext.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeed();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      idep_oracle_oracle_pb.Feed.serializeBinaryToWriter
    );
  }
  f = message.getServiceName();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getProvidersList();
  if (f.length > 0) {
    writer.writeRepeatedString(3, f);
  }
  f = message.getInput();
  if (f.length > 0) {
    writer.writeString(4, f);
  }
  f = message.getTimeout();
  if (f !== 0) {
    writer.writeInt64(5, f);
  }
  f = message.getServiceFeeCapList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getRepeatedFrequency();
  if (f !== 0) {
    writer.writeUint64(7, f);
  }
  f = message.getResponseThreshold();
  if (f !== 0) {
    writer.writeUint32(8, f);
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(9, f);
  }
};

/**
 * optional Feed feed = 1;
 * @return {?proto.idep.oracle.Feed}
 */
proto.idep.oracle.FeedContext.prototype.getFeed = function() {
  return /** @type{?proto.idep.oracle.Feed} */ (jspb.Message.getWrapperField(
    this,
    idep_oracle_oracle_pb.Feed,
    1
  ));
};

/**
 * @param {?proto.idep.oracle.Feed|undefined} value
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.setFeed = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.clearFeed = function() {
  return this.setFeed(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idep.oracle.FeedContext.prototype.hasFeed = function() {
  return jspb.Message.getField(this, 1) != null;
};

/**
 * optional string service_name = 2;
 * @return {string}
 */
proto.idep.oracle.FeedContext.prototype.getServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.setServiceName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * repeated string providers = 3;
 * @return {!Array<string>}
 */
proto.idep.oracle.FeedContext.prototype.getProvidersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};

/**
 * @param {!Array<string>} value
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.setProvidersList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};

/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.addProviders = function(
  value,
  opt_index
) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.clearProvidersList = function() {
  return this.setProvidersList([]);
};

/**
 * optional string input = 4;
 * @return {string}
 */
proto.idep.oracle.FeedContext.prototype.getInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.setInput = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * optional int64 timeout = 5;
 * @return {number}
 */
proto.idep.oracle.FeedContext.prototype.getTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.setTimeout = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};

/**
 * repeated cosmos.base.v1beta1.Coin service_fee_cap = 6;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.idep.oracle.FeedContext.prototype.getServiceFeeCapList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    cosmos_base_v1beta1_coin_pb.Coin,
    6
  ));
};

/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.setServiceFeeCapList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};

/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.idep.oracle.FeedContext.prototype.addServiceFeeCap = function(
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    6,
    opt_value,
    proto.cosmos.base.v1beta1.Coin,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.clearServiceFeeCapList = function() {
  return this.setServiceFeeCapList([]);
};

/**
 * optional uint64 repeated_frequency = 7;
 * @return {number}
 */
proto.idep.oracle.FeedContext.prototype.getRepeatedFrequency = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.setRepeatedFrequency = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};

/**
 * optional uint32 response_threshold = 8;
 * @return {number}
 */
proto.idep.oracle.FeedContext.prototype.getResponseThreshold = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.setResponseThreshold = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};

/**
 * optional idep.service.RequestContextState state = 9;
 * @return {!proto.idep.service.RequestContextState}
 */
proto.idep.oracle.FeedContext.prototype.getState = function() {
  return /** @type {!proto.idep.service.RequestContextState} */ (jspb.Message.getFieldWithDefault(
    this,
    9,
    0
  ));
};

/**
 * @param {!proto.idep.service.RequestContextState} value
 * @return {!proto.idep.oracle.FeedContext} returns this
 */
proto.idep.oracle.FeedContext.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};

goog.object.extend(exports, proto.idep.oracle);
