// source: idep/oracle/tx.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var cosmos_base_v1beta1_coin_pb = require('../../cosmos/base/v1beta1/coin_pb.js');
goog.object.extend(proto, cosmos_base_v1beta1_coin_pb);
goog.exportSymbol('proto.idep.oracle.MsgCreateFeed', null, global);
goog.exportSymbol('proto.idep.oracle.MsgCreateFeedResponse', null, global);
goog.exportSymbol('proto.idep.oracle.MsgEditFeed', null, global);
goog.exportSymbol('proto.idep.oracle.MsgEditFeedResponse', null, global);
goog.exportSymbol('proto.idep.oracle.MsgPauseFeed', null, global);
goog.exportSymbol('proto.idep.oracle.MsgPauseFeedResponse', null, global);
goog.exportSymbol('proto.idep.oracle.MsgStartFeed', null, global);
goog.exportSymbol('proto.idep.oracle.MsgStartFeedResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.MsgCreateFeed = function(opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.idep.oracle.MsgCreateFeed.repeatedFields_,
    null
  );
};
goog.inherits(proto.idep.oracle.MsgCreateFeed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.MsgCreateFeed.displayName =
    'proto.idep.oracle.MsgCreateFeed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.MsgCreateFeedResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.MsgCreateFeedResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.MsgCreateFeedResponse.displayName =
    'proto.idep.oracle.MsgCreateFeedResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.MsgStartFeed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.MsgStartFeed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.MsgStartFeed.displayName = 'proto.idep.oracle.MsgStartFeed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.MsgStartFeedResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.MsgStartFeedResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.MsgStartFeedResponse.displayName =
    'proto.idep.oracle.MsgStartFeedResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.MsgPauseFeed = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.MsgPauseFeed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.MsgPauseFeed.displayName = 'proto.idep.oracle.MsgPauseFeed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.MsgPauseFeedResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.MsgPauseFeedResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.MsgPauseFeedResponse.displayName =
    'proto.idep.oracle.MsgPauseFeedResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.MsgEditFeed = function(opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.idep.oracle.MsgEditFeed.repeatedFields_,
    null
  );
};
goog.inherits(proto.idep.oracle.MsgEditFeed, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.MsgEditFeed.displayName = 'proto.idep.oracle.MsgEditFeed';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.oracle.MsgEditFeedResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idep.oracle.MsgEditFeedResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.oracle.MsgEditFeedResponse.displayName =
    'proto.idep.oracle.MsgEditFeedResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idep.oracle.MsgCreateFeed.repeatedFields_ = [6, 9];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.MsgCreateFeed.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.MsgCreateFeed.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.MsgCreateFeed} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.MsgCreateFeed.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        feedName: jspb.Message.getFieldWithDefault(msg, 1, ''),
        latestHistory: jspb.Message.getFieldWithDefault(msg, 2, 0),
        description: jspb.Message.getFieldWithDefault(msg, 3, ''),
        creator: jspb.Message.getFieldWithDefault(msg, 4, ''),
        serviceName: jspb.Message.getFieldWithDefault(msg, 5, ''),
        providersList:
          (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
        input: jspb.Message.getFieldWithDefault(msg, 7, ''),
        timeout: jspb.Message.getFieldWithDefault(msg, 8, 0),
        serviceFeeCapList: jspb.Message.toObjectList(
          msg.getServiceFeeCapList(),
          cosmos_base_v1beta1_coin_pb.Coin.toObject,
          includeInstance
        ),
        repeatedFrequency: jspb.Message.getFieldWithDefault(msg, 10, 0),
        aggregateFunc: jspb.Message.getFieldWithDefault(msg, 11, ''),
        valueJsonPath: jspb.Message.getFieldWithDefault(msg, 12, ''),
        responseThreshold: jspb.Message.getFieldWithDefault(msg, 13, 0),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.MsgCreateFeed}
 */
proto.idep.oracle.MsgCreateFeed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.MsgCreateFeed();
  return proto.idep.oracle.MsgCreateFeed.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.MsgCreateFeed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.MsgCreateFeed}
 */
proto.idep.oracle.MsgCreateFeed.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setFeedName(value);
        break;
      case 2:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setLatestHistory(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setDescription(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setCreator(value);
        break;
      case 5:
        var value = /** @type {string} */ (reader.readString());
        msg.setServiceName(value);
        break;
      case 6:
        var value = /** @type {string} */ (reader.readString());
        msg.addProviders(value);
        break;
      case 7:
        var value = /** @type {string} */ (reader.readString());
        msg.setInput(value);
        break;
      case 8:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setTimeout(value);
        break;
      case 9:
        var value = new cosmos_base_v1beta1_coin_pb.Coin();
        reader.readMessage(
          value,
          cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader
        );
        msg.addServiceFeeCap(value);
        break;
      case 10:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setRepeatedFrequency(value);
        break;
      case 11:
        var value = /** @type {string} */ (reader.readString());
        msg.setAggregateFunc(value);
        break;
      case 12:
        var value = /** @type {string} */ (reader.readString());
        msg.setValueJsonPath(value);
        break;
      case 13:
        var value = /** @type {number} */ (reader.readUint32());
        msg.setResponseThreshold(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.MsgCreateFeed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.MsgCreateFeed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.MsgCreateFeed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.MsgCreateFeed.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeedName();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getLatestHistory();
  if (f !== 0) {
    writer.writeUint64(2, f);
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
  f = message.getCreator();
  if (f.length > 0) {
    writer.writeString(4, f);
  }
  f = message.getServiceName();
  if (f.length > 0) {
    writer.writeString(5, f);
  }
  f = message.getProvidersList();
  if (f.length > 0) {
    writer.writeRepeatedString(6, f);
  }
  f = message.getInput();
  if (f.length > 0) {
    writer.writeString(7, f);
  }
  f = message.getTimeout();
  if (f !== 0) {
    writer.writeInt64(8, f);
  }
  f = message.getServiceFeeCapList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getRepeatedFrequency();
  if (f !== 0) {
    writer.writeUint64(10, f);
  }
  f = message.getAggregateFunc();
  if (f.length > 0) {
    writer.writeString(11, f);
  }
  f = message.getValueJsonPath();
  if (f.length > 0) {
    writer.writeString(12, f);
  }
  f = message.getResponseThreshold();
  if (f !== 0) {
    writer.writeUint32(13, f);
  }
};

/**
 * optional string feed_name = 1;
 * @return {string}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getFeedName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setFeedName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional uint64 latest_history = 2;
 * @return {number}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getLatestHistory = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setLatestHistory = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};

/**
 * optional string description = 3;
 * @return {string}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

/**
 * optional string creator = 4;
 * @return {string}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getCreator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setCreator = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};

/**
 * optional string service_name = 5;
 * @return {string}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getServiceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setServiceName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};

/**
 * repeated string providers = 6;
 * @return {!Array<string>}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getProvidersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};

/**
 * @param {!Array<string>} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setProvidersList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};

/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.addProviders = function(
  value,
  opt_index
) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.clearProvidersList = function() {
  return this.setProvidersList([]);
};

/**
 * optional string input = 7;
 * @return {string}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getInput = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setInput = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};

/**
 * optional int64 timeout = 8;
 * @return {number}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setTimeout = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};

/**
 * repeated cosmos.base.v1beta1.Coin service_fee_cap = 9;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getServiceFeeCapList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    cosmos_base_v1beta1_coin_pb.Coin,
    9
  ));
};

/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setServiceFeeCapList = function(
  value
) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};

/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.idep.oracle.MsgCreateFeed.prototype.addServiceFeeCap = function(
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    9,
    opt_value,
    proto.cosmos.base.v1beta1.Coin,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.clearServiceFeeCapList = function() {
  return this.setServiceFeeCapList([]);
};

/**
 * optional uint64 repeated_frequency = 10;
 * @return {number}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getRepeatedFrequency = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setRepeatedFrequency = function(
  value
) {
  return jspb.Message.setProto3IntField(this, 10, value);
};

/**
 * optional string aggregate_func = 11;
 * @return {string}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getAggregateFunc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setAggregateFunc = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};

/**
 * optional string value_json_path = 12;
 * @return {string}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getValueJsonPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setValueJsonPath = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};

/**
 * optional uint32 response_threshold = 13;
 * @return {number}
 */
proto.idep.oracle.MsgCreateFeed.prototype.getResponseThreshold = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.MsgCreateFeed} returns this
 */
proto.idep.oracle.MsgCreateFeed.prototype.setResponseThreshold = function(
  value
) {
  return jspb.Message.setProto3IntField(this, 13, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.MsgCreateFeedResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.MsgCreateFeedResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.MsgCreateFeedResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.MsgCreateFeedResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {};

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.MsgCreateFeedResponse}
 */
proto.idep.oracle.MsgCreateFeedResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.MsgCreateFeedResponse();
  return proto.idep.oracle.MsgCreateFeedResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.MsgCreateFeedResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.MsgCreateFeedResponse}
 */
proto.idep.oracle.MsgCreateFeedResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.MsgCreateFeedResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.MsgCreateFeedResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.MsgCreateFeedResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.MsgCreateFeedResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.MsgStartFeed.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.MsgStartFeed.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.MsgStartFeed} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.MsgStartFeed.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        feedName: jspb.Message.getFieldWithDefault(msg, 1, ''),
        creator: jspb.Message.getFieldWithDefault(msg, 2, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.MsgStartFeed}
 */
proto.idep.oracle.MsgStartFeed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.MsgStartFeed();
  return proto.idep.oracle.MsgStartFeed.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.MsgStartFeed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.MsgStartFeed}
 */
proto.idep.oracle.MsgStartFeed.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setFeedName(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setCreator(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.MsgStartFeed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.MsgStartFeed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.MsgStartFeed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.MsgStartFeed.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeedName();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getCreator();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
};

/**
 * optional string feed_name = 1;
 * @return {string}
 */
proto.idep.oracle.MsgStartFeed.prototype.getFeedName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgStartFeed} returns this
 */
proto.idep.oracle.MsgStartFeed.prototype.setFeedName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string creator = 2;
 * @return {string}
 */
proto.idep.oracle.MsgStartFeed.prototype.getCreator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgStartFeed} returns this
 */
proto.idep.oracle.MsgStartFeed.prototype.setCreator = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.MsgStartFeedResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.MsgStartFeedResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.MsgStartFeedResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.MsgStartFeedResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {};

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.MsgStartFeedResponse}
 */
proto.idep.oracle.MsgStartFeedResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.MsgStartFeedResponse();
  return proto.idep.oracle.MsgStartFeedResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.MsgStartFeedResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.MsgStartFeedResponse}
 */
proto.idep.oracle.MsgStartFeedResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.MsgStartFeedResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.MsgStartFeedResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.MsgStartFeedResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.MsgStartFeedResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.MsgPauseFeed.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.MsgPauseFeed.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.MsgPauseFeed} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.MsgPauseFeed.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        feedName: jspb.Message.getFieldWithDefault(msg, 1, ''),
        creator: jspb.Message.getFieldWithDefault(msg, 2, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.MsgPauseFeed}
 */
proto.idep.oracle.MsgPauseFeed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.MsgPauseFeed();
  return proto.idep.oracle.MsgPauseFeed.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.MsgPauseFeed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.MsgPauseFeed}
 */
proto.idep.oracle.MsgPauseFeed.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setFeedName(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setCreator(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.MsgPauseFeed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.MsgPauseFeed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.MsgPauseFeed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.MsgPauseFeed.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeedName();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getCreator();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
};

/**
 * optional string feed_name = 1;
 * @return {string}
 */
proto.idep.oracle.MsgPauseFeed.prototype.getFeedName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgPauseFeed} returns this
 */
proto.idep.oracle.MsgPauseFeed.prototype.setFeedName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string creator = 2;
 * @return {string}
 */
proto.idep.oracle.MsgPauseFeed.prototype.getCreator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgPauseFeed} returns this
 */
proto.idep.oracle.MsgPauseFeed.prototype.setCreator = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.MsgPauseFeedResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.MsgPauseFeedResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.MsgPauseFeedResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.MsgPauseFeedResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {};

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.MsgPauseFeedResponse}
 */
proto.idep.oracle.MsgPauseFeedResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.MsgPauseFeedResponse();
  return proto.idep.oracle.MsgPauseFeedResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.MsgPauseFeedResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.MsgPauseFeedResponse}
 */
proto.idep.oracle.MsgPauseFeedResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.MsgPauseFeedResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.MsgPauseFeedResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.MsgPauseFeedResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.MsgPauseFeedResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
};

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idep.oracle.MsgEditFeed.repeatedFields_ = [4, 6];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.MsgEditFeed.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.MsgEditFeed.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.MsgEditFeed} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.MsgEditFeed.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        feedName: jspb.Message.getFieldWithDefault(msg, 1, ''),
        description: jspb.Message.getFieldWithDefault(msg, 2, ''),
        latestHistory: jspb.Message.getFieldWithDefault(msg, 3, 0),
        providersList:
          (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
        timeout: jspb.Message.getFieldWithDefault(msg, 5, 0),
        serviceFeeCapList: jspb.Message.toObjectList(
          msg.getServiceFeeCapList(),
          cosmos_base_v1beta1_coin_pb.Coin.toObject,
          includeInstance
        ),
        repeatedFrequency: jspb.Message.getFieldWithDefault(msg, 7, 0),
        responseThreshold: jspb.Message.getFieldWithDefault(msg, 8, 0),
        creator: jspb.Message.getFieldWithDefault(msg, 9, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.MsgEditFeed}
 */
proto.idep.oracle.MsgEditFeed.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.MsgEditFeed();
  return proto.idep.oracle.MsgEditFeed.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.MsgEditFeed} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.MsgEditFeed}
 */
proto.idep.oracle.MsgEditFeed.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setFeedName(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setDescription(value);
        break;
      case 3:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setLatestHistory(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.addProviders(value);
        break;
      case 5:
        var value = /** @type {number} */ (reader.readInt64());
        msg.setTimeout(value);
        break;
      case 6:
        var value = new cosmos_base_v1beta1_coin_pb.Coin();
        reader.readMessage(
          value,
          cosmos_base_v1beta1_coin_pb.Coin.deserializeBinaryFromReader
        );
        msg.addServiceFeeCap(value);
        break;
      case 7:
        var value = /** @type {number} */ (reader.readUint64());
        msg.setRepeatedFrequency(value);
        break;
      case 8:
        var value = /** @type {number} */ (reader.readUint32());
        msg.setResponseThreshold(value);
        break;
      case 9:
        var value = /** @type {string} */ (reader.readString());
        msg.setCreator(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.MsgEditFeed.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.MsgEditFeed.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.MsgEditFeed} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.MsgEditFeed.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getFeedName();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getLatestHistory();
  if (f !== 0) {
    writer.writeUint64(3, f);
  }
  f = message.getProvidersList();
  if (f.length > 0) {
    writer.writeRepeatedString(4, f);
  }
  f = message.getTimeout();
  if (f !== 0) {
    writer.writeInt64(5, f);
  }
  f = message.getServiceFeeCapList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      cosmos_base_v1beta1_coin_pb.Coin.serializeBinaryToWriter
    );
  }
  f = message.getRepeatedFrequency();
  if (f !== 0) {
    writer.writeUint64(7, f);
  }
  f = message.getResponseThreshold();
  if (f !== 0) {
    writer.writeUint32(8, f);
  }
  f = message.getCreator();
  if (f.length > 0) {
    writer.writeString(9, f);
  }
};

/**
 * optional string feed_name = 1;
 * @return {string}
 */
proto.idep.oracle.MsgEditFeed.prototype.getFeedName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.setFeedName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string description = 2;
 * @return {string}
 */
proto.idep.oracle.MsgEditFeed.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * optional uint64 latest_history = 3;
 * @return {number}
 */
proto.idep.oracle.MsgEditFeed.prototype.getLatestHistory = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.setLatestHistory = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};

/**
 * repeated string providers = 4;
 * @return {!Array<string>}
 */
proto.idep.oracle.MsgEditFeed.prototype.getProvidersList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};

/**
 * @param {!Array<string>} value
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.setProvidersList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};

/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.addProviders = function(
  value,
  opt_index
) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.clearProvidersList = function() {
  return this.setProvidersList([]);
};

/**
 * optional int64 timeout = 5;
 * @return {number}
 */
proto.idep.oracle.MsgEditFeed.prototype.getTimeout = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.setTimeout = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};

/**
 * repeated cosmos.base.v1beta1.Coin service_fee_cap = 6;
 * @return {!Array<!proto.cosmos.base.v1beta1.Coin>}
 */
proto.idep.oracle.MsgEditFeed.prototype.getServiceFeeCapList = function() {
  return /** @type{!Array<!proto.cosmos.base.v1beta1.Coin>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    cosmos_base_v1beta1_coin_pb.Coin,
    6
  ));
};

/**
 * @param {!Array<!proto.cosmos.base.v1beta1.Coin>} value
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.setServiceFeeCapList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};

/**
 * @param {!proto.cosmos.base.v1beta1.Coin=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cosmos.base.v1beta1.Coin}
 */
proto.idep.oracle.MsgEditFeed.prototype.addServiceFeeCap = function(
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    6,
    opt_value,
    proto.cosmos.base.v1beta1.Coin,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.clearServiceFeeCapList = function() {
  return this.setServiceFeeCapList([]);
};

/**
 * optional uint64 repeated_frequency = 7;
 * @return {number}
 */
proto.idep.oracle.MsgEditFeed.prototype.getRepeatedFrequency = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.setRepeatedFrequency = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};

/**
 * optional uint32 response_threshold = 8;
 * @return {number}
 */
proto.idep.oracle.MsgEditFeed.prototype.getResponseThreshold = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};

/**
 * @param {number} value
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.setResponseThreshold = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};

/**
 * optional string creator = 9;
 * @return {string}
 */
proto.idep.oracle.MsgEditFeed.prototype.getCreator = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ''));
};

/**
 * @param {string} value
 * @return {!proto.idep.oracle.MsgEditFeed} returns this
 */
proto.idep.oracle.MsgEditFeed.prototype.setCreator = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.oracle.MsgEditFeedResponse.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.oracle.MsgEditFeedResponse.toObject(
      opt_includeInstance,
      this
    );
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.oracle.MsgEditFeedResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.oracle.MsgEditFeedResponse.toObject = function(
    includeInstance,
    msg
  ) {
    var f,
      obj = {};

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.oracle.MsgEditFeedResponse}
 */
proto.idep.oracle.MsgEditFeedResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.oracle.MsgEditFeedResponse();
  return proto.idep.oracle.MsgEditFeedResponse.deserializeBinaryFromReader(
    msg,
    reader
  );
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.oracle.MsgEditFeedResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.oracle.MsgEditFeedResponse}
 */
proto.idep.oracle.MsgEditFeedResponse.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.oracle.MsgEditFeedResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.oracle.MsgEditFeedResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.oracle.MsgEditFeedResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.oracle.MsgEditFeedResponse.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
};

goog.object.extend(exports, proto.idep.oracle);
