// source: idep/htlc/genesis.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var gogoproto_gogo_pb = require('../../gogoproto/gogo_pb.js');
goog.object.extend(proto, gogoproto_gogo_pb);
var idep_htlc_htlc_pb = require('../../idep/htlc/htlc_pb.js');
goog.object.extend(proto, idep_htlc_htlc_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.idep.htlc.GenesisState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idep.htlc.GenesisState = function(opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.idep.htlc.GenesisState.repeatedFields_,
    null
  );
};
goog.inherits(proto.idep.htlc.GenesisState, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idep.htlc.GenesisState.displayName = 'proto.idep.htlc.GenesisState';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idep.htlc.GenesisState.repeatedFields_ = [2, 3];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.idep.htlc.GenesisState.prototype.toObject = function(
    opt_includeInstance
  ) {
    return proto.idep.htlc.GenesisState.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.idep.htlc.GenesisState} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.idep.htlc.GenesisState.toObject = function(includeInstance, msg) {
    var f,
      obj = {
        params:
          (f = msg.getParams()) &&
          idep_htlc_htlc_pb.Params.toObject(includeInstance, f),
        htlcsList: jspb.Message.toObjectList(
          msg.getHtlcsList(),
          idep_htlc_htlc_pb.HTLC.toObject,
          includeInstance
        ),
        suppliesList: jspb.Message.toObjectList(
          msg.getSuppliesList(),
          idep_htlc_htlc_pb.AssetSupply.toObject,
          includeInstance
        ),
        previousBlockTime:
          (f = msg.getPreviousBlockTime()) &&
          google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idep.htlc.GenesisState}
 */
proto.idep.htlc.GenesisState.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idep.htlc.GenesisState();
  return proto.idep.htlc.GenesisState.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idep.htlc.GenesisState} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idep.htlc.GenesisState}
 */
proto.idep.htlc.GenesisState.deserializeBinaryFromReader = function(
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new idep_htlc_htlc_pb.Params();
        reader.readMessage(
          value,
          idep_htlc_htlc_pb.Params.deserializeBinaryFromReader
        );
        msg.setParams(value);
        break;
      case 2:
        var value = new idep_htlc_htlc_pb.HTLC();
        reader.readMessage(
          value,
          idep_htlc_htlc_pb.HTLC.deserializeBinaryFromReader
        );
        msg.addHtlcs(value);
        break;
      case 3:
        var value = new idep_htlc_htlc_pb.AssetSupply();
        reader.readMessage(
          value,
          idep_htlc_htlc_pb.AssetSupply.deserializeBinaryFromReader
        );
        msg.addSupplies(value);
        break;
      case 4:
        var value = new google_protobuf_timestamp_pb.Timestamp();
        reader.readMessage(
          value,
          google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader
        );
        msg.setPreviousBlockTime(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idep.htlc.GenesisState.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idep.htlc.GenesisState.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idep.htlc.GenesisState} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idep.htlc.GenesisState.serializeBinaryToWriter = function(
  message,
  writer
) {
  var f = undefined;
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(1, f, idep_htlc_htlc_pb.Params.serializeBinaryToWriter);
  }
  f = message.getHtlcsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      idep_htlc_htlc_pb.HTLC.serializeBinaryToWriter
    );
  }
  f = message.getSuppliesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      idep_htlc_htlc_pb.AssetSupply.serializeBinaryToWriter
    );
  }
  f = message.getPreviousBlockTime();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};

/**
 * optional Params params = 1;
 * @return {?proto.idep.htlc.Params}
 */
proto.idep.htlc.GenesisState.prototype.getParams = function() {
  return /** @type{?proto.idep.htlc.Params} */ (jspb.Message.getWrapperField(
    this,
    idep_htlc_htlc_pb.Params,
    1
  ));
};

/**
 * @param {?proto.idep.htlc.Params|undefined} value
 * @return {!proto.idep.htlc.GenesisState} returns this
 */
proto.idep.htlc.GenesisState.prototype.setParams = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.idep.htlc.GenesisState} returns this
 */
proto.idep.htlc.GenesisState.prototype.clearParams = function() {
  return this.setParams(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idep.htlc.GenesisState.prototype.hasParams = function() {
  return jspb.Message.getField(this, 1) != null;
};

/**
 * repeated HTLC htlcs = 2;
 * @return {!Array<!proto.idep.htlc.HTLC>}
 */
proto.idep.htlc.GenesisState.prototype.getHtlcsList = function() {
  return /** @type{!Array<!proto.idep.htlc.HTLC>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    idep_htlc_htlc_pb.HTLC,
    2
  ));
};

/**
 * @param {!Array<!proto.idep.htlc.HTLC>} value
 * @return {!proto.idep.htlc.GenesisState} returns this
 */
proto.idep.htlc.GenesisState.prototype.setHtlcsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};

/**
 * @param {!proto.idep.htlc.HTLC=} opt_value
 * @param {number=} opt_index
 * @return {!proto.idep.htlc.HTLC}
 */
proto.idep.htlc.GenesisState.prototype.addHtlcs = function(
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    2,
    opt_value,
    proto.idep.htlc.HTLC,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.htlc.GenesisState} returns this
 */
proto.idep.htlc.GenesisState.prototype.clearHtlcsList = function() {
  return this.setHtlcsList([]);
};

/**
 * repeated AssetSupply supplies = 3;
 * @return {!Array<!proto.idep.htlc.AssetSupply>}
 */
proto.idep.htlc.GenesisState.prototype.getSuppliesList = function() {
  return /** @type{!Array<!proto.idep.htlc.AssetSupply>} */ (jspb.Message.getRepeatedWrapperField(
    this,
    idep_htlc_htlc_pb.AssetSupply,
    3
  ));
};

/**
 * @param {!Array<!proto.idep.htlc.AssetSupply>} value
 * @return {!proto.idep.htlc.GenesisState} returns this
 */
proto.idep.htlc.GenesisState.prototype.setSuppliesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};

/**
 * @param {!proto.idep.htlc.AssetSupply=} opt_value
 * @param {number=} opt_index
 * @return {!proto.idep.htlc.AssetSupply}
 */
proto.idep.htlc.GenesisState.prototype.addSupplies = function(
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    3,
    opt_value,
    proto.idep.htlc.AssetSupply,
    opt_index
  );
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idep.htlc.GenesisState} returns this
 */
proto.idep.htlc.GenesisState.prototype.clearSuppliesList = function() {
  return this.setSuppliesList([]);
};

/**
 * optional google.protobuf.Timestamp previous_block_time = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.idep.htlc.GenesisState.prototype.getPreviousBlockTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (jspb.Message.getWrapperField(
    this,
    google_protobuf_timestamp_pb.Timestamp,
    4
  ));
};

/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.idep.htlc.GenesisState} returns this
 */
proto.idep.htlc.GenesisState.prototype.setPreviousBlockTime = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.idep.htlc.GenesisState} returns this
 */
proto.idep.htlc.GenesisState.prototype.clearPreviousBlockTime = function() {
  return this.setPreviousBlockTime(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idep.htlc.GenesisState.prototype.hasPreviousBlockTime = function() {
  return jspb.Message.getField(this, 4) != null;
};

goog.object.extend(exports, proto.idep.htlc);
